// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d6bab2f5-814b-433f-91a9-1ac1fe52fa1b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_omLqykAil",
    "aws_user_pools_web_client_id": "17qfj654886c1lk6rdv9kp1h3i",
    "aws_appsync_graphqlEndpoint": "https://c47p7t3csbf6zkm5f722jss36y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "projectportfolio-20181217174051-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://projectportfolio-20181217174051-hostingbucket.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
